### ISSUE TITLE
下方留言建議縮小頭像、放大留言字體大小

### ISSUE THREAD

**Issue by Griiid** [init-engineer/init.engineer-iOS-App#21]
留言文字太小有點難以閱讀
建議可以把文字放大，然後頭像再縮小一點讓留言的文字空間多一點

**Comment by tico88612** [comment]
前陣子有加入新功能 Plurk 圖片瀏覽，為了相容 HTML Tag 就放棄了 UILabel，就變成不是預設的大小，下一版會調整

**Comment by tico88612** [comment]
https://github.com/init-engineer/init.engineer-iOS-App/commit/2ac7f518f27f6af3b04c7bbd38d94f142212d473
